# Generated by Django 3.2.8 on 2021-10-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Departement',
            new_name='Department',
        ),
    ]
